// ============================================================
// src/modules/voucher/VoucherDetailScreen.tsx
// ============================================================

import React, { useEffect, useState } from "react";
import {
  View,
  ScrollView,
  StyleSheet,
  Text,
  Alert,
} from "react-native";
import { Voucher, VoucherDetail, VoucherType } from "../../api/types";
import { fetchVoucherById, deleteVoucher } from "./api";
import Loader from "../../shared/components/Loader";
import SectionTitle from "../../shared/components/SectionTitle";
import AppButton from "../../shared/components/AppButton";
import { formatNumber } from "../../shared/utils/number";
import { useThemeStore } from "../../store/themeStore";

const TYPE_COLOR: Record<VoucherType, string> = {
  Receipt: "#1E9E5A",
  Payment: "#D64545",
  Journal: "#2563EB",
};

type Props = {
  route: { params?: { voucherId?: number } };
  navigation: any;
};

export default function VoucherDetailScreen({ route, navigation }: Props) {
  const voucherId = Number(route?.params?.voucherId);
  const { theme } = useThemeStore();
  const colors = theme.colors;

  const [voucher, setVoucher] = useState<Voucher | null>(null);
  const [details, setDetails] = useState<VoucherDetail[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        if (!voucherId || voucherId <= 0) {
          Alert.alert("Error", "Invalid voucher ID");
          navigation.goBack?.();
          return;
        }

        const res = await fetchVoucherById(voucherId);
        setVoucher(res.voucher);
        setDetails(Array.isArray(res.details) ? res.details : []);
      } catch (e: any) {
        Alert.alert(
          "Error",
          e?.response?.data?.message || e?.message || "Failed to load voucher"
        );
        navigation.goBack?.();
      } finally {
        setLoading(false);
      }
    })();
  }, [voucherId]);

  const handleDelete = async () => {
    if (!voucher?.voucher_id) return;

    const ref = voucher.reference_no ?? "";
    if (ref.startsWith("BILL:") || ref.startsWith("REFUND:")) {
      Alert.alert(
        "Not allowed",
        "This voucher was auto-generated by a bill/refund flow. To reverse it, modify the source transaction."
      );
      return;
    }

    Alert.alert(
      "Delete Voucher",
      `Delete ${voucher.voucher_no}? This action cannot be undone.`,
      [
        { text: "Cancel", style: "cancel" },
        {
          text: "Delete",
          style: "destructive",
          onPress: async () => {
            try {
              await deleteVoucher(voucher.voucher_id!);
              Alert.alert("Deleted", "Voucher deleted", [
                { text: "OK", onPress: () => navigation.goBack?.() },
              ]);
            } catch (e: any) {
              Alert.alert(
                "Error",
                e?.response?.data?.message || e?.message || "Cannot delete voucher"
              );
            }
          },
        },
      ]
    );
  };

  if (loading) return <Loader />;
  if (!voucher) return null;

  const vType = voucher.voucher_type as VoucherType;
  const typeColor = TYPE_COLOR[vType] ?? "#6B7280";

  const totalDr = details.reduce((s, d) => s + Number(d.dr_amount || 0), 0);
  const totalCr = details.reduce((s, d) => s + Number(d.cr_amount || 0), 0);
  const isBalanced = Math.abs(totalDr - totalCr) < 0.01;

  const isAutoVoucher =
    (voucher.reference_no ?? "").startsWith("BILL:") ||
    (voucher.reference_no ?? "").startsWith("REFUND:");

  return (
    <View style={[styles.wrapper, { backgroundColor: colors.background }]}>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={{ paddingBottom: 40 }}
        showsVerticalScrollIndicator={false}
      >
        <SectionTitle title="Voucher Detail" subtitle={voucher.voucher_no} />

        {isAutoVoucher && (
          <View
            style={[
              styles.notice,
              { backgroundColor: "#D98E0412", borderColor: "#D98E0440" },
            ]}
          >
            <Text style={[styles.noticeText, { color: "#D98E04" }]}>
              Auto-generated by bill/refund flow. This voucher cannot be deleted here.
            </Text>
          </View>
        )}

        <View
          style={[
            styles.headerCard,
            {
              backgroundColor: colors.surface,
              borderColor: colors.border,
              borderLeftColor: typeColor,
              borderLeftWidth: 4,
            },
          ]}
        >
          <View style={styles.topRow}>
            <Text style={[styles.voucherNo, { color: colors.text }]}>
              {voucher.voucher_no}
            </Text>
            <View style={[styles.badge, { backgroundColor: `${typeColor}18` }]}>
              <Text style={[styles.badgeText, { color: typeColor }]}>{vType}</Text>
            </View>
          </View>

          <MetaRow
            label="Date"
            value={voucher.voucher_date?.slice(0, 10) ?? "—"}
            colors={colors}
          />
          {voucher.narration ? (
            <MetaRow label="Narration" value={voucher.narration} colors={colors} />
          ) : null}
          {voucher.reference_no ? (
            <MetaRow label="Reference" value={voucher.reference_no} colors={colors} />
          ) : null}

          <View style={[styles.balanceRow, { borderTopColor: colors.border }]}>
            <Text style={[styles.balanceLabel, { color: colors.textSecondary }]}>
              Voucher Balance
            </Text>
            <Text
              style={[
                styles.balanceValue,
                { color: isBalanced ? "#1E9E5A" : "#D64545" },
              ]}
            >
              {isBalanced
                ? "✓ Balanced"
                : `✗ Dr ${formatNumber(totalDr, 2)} / Cr ${formatNumber(totalCr, 2)}`}
            </Text>
          </View>
        </View>

        {details.length === 0 ? (
          <View
            style={[
              styles.emptyCard,
              { backgroundColor: colors.surface, borderColor: colors.border },
            ]}
          >
            <Text style={{ color: colors.textSecondary }}>No detail entries found.</Text>
          </View>
        ) : (
          <>
            <View
              style={[
                styles.tableHeader,
                { backgroundColor: `${typeColor}18`, borderColor: typeColor },
              ]}
            >
              <Text style={[styles.colLedger, styles.colHead, { color: typeColor }]}>
                Ledger
              </Text>
              <Text style={[styles.colType, styles.colHead, { color: typeColor }]}>
                Type
              </Text>
              <Text style={[styles.colDr, styles.colHead, { color: typeColor }]}>
                Dr
              </Text>
              <Text style={[styles.colCr, styles.colHead, { color: typeColor }]}>
                Cr
              </Text>
            </View>

            {details.map((line, idx) => (
              <View
                key={line.voucher_detail_id ?? idx}
                style={[
                  styles.tableRow,
                  {
                    backgroundColor: idx % 2 === 0 ? colors.surface : colors.background,
                    borderColor: colors.border,
                  },
                ]}
              >
                <Text
                  style={[styles.colLedger, styles.cellText, { color: colors.text }]}
                  numberOfLines={2}
                >
                  {line.ledger_name || `Ledger #${line.ledger_id}`}
                </Text>
                <Text
                  style={[styles.colType, styles.cellSub, { color: colors.textSecondary }]}
                >
                  {line.ledger_type ?? "—"}
                </Text>
                <Text
                  style={[
                    styles.colDr,
                    styles.cellText,
                    { color: line.dr_amount > 0 ? "#D64545" : colors.textSecondary },
                  ]}
                >
                  {line.dr_amount > 0 ? formatNumber(Number(line.dr_amount), 2) : "—"}
                </Text>
                <Text
                  style={[
                    styles.colCr,
                    styles.cellText,
                    { color: line.cr_amount > 0 ? "#1E9E5A" : colors.textSecondary },
                  ]}
                >
                  {line.cr_amount > 0 ? formatNumber(Number(line.cr_amount), 2) : "—"}
                </Text>
              </View>
            ))}

            <View
              style={[
                styles.totalsRow,
                { backgroundColor: `${typeColor}10`, borderColor: typeColor },
              ]}
            >
              <Text style={[styles.colLedger, styles.totalsText, { color: colors.text }]}>
                Total ({details.length} entries)
              </Text>
              <Text style={[styles.colType, styles.totalsText, { color: colors.text }]} />
              <Text style={[styles.colDr, styles.totalsText, { color: "#D64545" }]}>
                {formatNumber(totalDr, 2)}
              </Text>
              <Text style={[styles.colCr, styles.totalsText, { color: "#1E9E5A" }]}>
                {formatNumber(totalCr, 2)}
              </Text>
            </View>
          </>
        )}

        {!isAutoVoucher && (
          <AppButton
            title="Delete Voucher"
            variant="outline"
            onPress={handleDelete}
            style={{ marginTop: 20 }}
          />
        )}

        <AppButton
          title="Back"
          variant="outline"
          onPress={() => navigation.goBack?.()}
          style={{ marginTop: 10 }}
        />
      </ScrollView>
    </View>
  );
}

const MetaRow: React.FC<{ label: string; value: string; colors: any }> = ({
  label,
  value,
  colors,
}) => (
  <View style={metaStyles.row}>
    <Text style={[metaStyles.label, { color: colors.textSecondary }]}>{label}</Text>
    <Text style={[metaStyles.value, { color: colors.text }]} numberOfLines={2}>
      {value}
    </Text>
  </View>
);

const metaStyles = StyleSheet.create({
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 5,
  },
  label: { fontSize: 13, flex: 1 },
  value: { fontSize: 13, fontWeight: "600", flex: 2, textAlign: "right" },
});

const styles = StyleSheet.create({
  wrapper: { flex: 1 },
  scroll: { flex: 1, padding: 16 },

  notice: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 14,
  },
  noticeText: { fontSize: 13, lineHeight: 20 },

  headerCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  voucherNo: { fontSize: 18, fontWeight: "700" },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  badgeText: { fontSize: 13, fontWeight: "700" },

  balanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    marginTop: 10,
    paddingTop: 10,
  },
  balanceLabel: { fontSize: 13 },
  balanceValue: { fontSize: 13, fontWeight: "700" },

  tableHeader: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginBottom: 2,
    alignItems: "center",
  },
  tableRow: {
    flexDirection: "row",
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: "center",
    marginBottom: 1,
  },
  totalsRow: {
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginTop: 4,
    alignItems: "center",
  },

  colHead: { fontSize: 11, fontWeight: "700" },
  cellText: { fontSize: 13 },
  cellSub: { fontSize: 11 },
  totalsText: { fontSize: 13, fontWeight: "700" },

  colLedger: { flex: 1, paddingRight: 6 },
  colType: { width: 70 },
  colDr: { width: 64, textAlign: "right" },
  colCr: { width: 64, textAlign: "right" },

  emptyCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    marginBottom: 14,
  },
});