// ============================================================
// src/modules/voucher/VoucherListScreen.tsx
// ============================================================

import React, { useCallback, useEffect, useState } from "react";
import {
  View,
  FlatList,
  StyleSheet,
  Text,
  TouchableOpacity,
  RefreshControl,
  Alert,
  Platform,
} from "react-native";
import { useNavigation, useIsFocused } from "@react-navigation/native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { Voucher, VoucherType } from "../../api/types";
import { fetchVoucherList, deleteVoucher } from "./api";
import Loader from "../../shared/components/Loader";
import SectionTitle from "../../shared/components/SectionTitle";
import AppButton from "../../shared/components/AppButton";
import Pill from "../../shared/components/Pill";
import { formatDateTime } from "../../shared/utils/date";
import { formatNumber } from "../../shared/utils/number";
import { useThemeStore } from "../../store/themeStore";

type TypeFilter = "All" | VoucherType;

const TYPE_FILTERS: TypeFilter[] = ["All", "Receipt", "Payment", "Journal"];

const TYPE_COLOR: Record<VoucherType, string> = {
  Receipt: "#1E9E5A",
  Payment: "#D64545",
  Journal: "#2563EB",
};

function todayIST(): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Kolkata",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
}

function thirtyDaysAgo(): string {
  const d = new Date();
  d.setDate(d.getDate() - 30);
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Asia/Kolkata",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(d);
}

const VoucherListScreen: React.FC = () => {
  const navigation = useNavigation<any>();
  const isFocused = useIsFocused();
  const { theme } = useThemeStore();
  const colors = theme.colors;

  const [data, setData] = useState<Voucher[]>([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [typeFilter, setTypeFilter] = useState<TypeFilter>("All");

  const [fromDate, setFromDate] = useState(thirtyDaysAgo());
  const [toDate, setToDate] = useState(todayIST());
  const [showFrom, setShowFrom] = useState(false);
  const [showTo, setShowTo] = useState(false);

  const load = useCallback(async () => {
    try {
      setLoading(true);
      const params: { fromDate?: string; toDate?: string; type?: VoucherType } = {
        fromDate,
        toDate,
      };
      if (typeFilter !== "All") params.type = typeFilter;
      const res = await fetchVoucherList(params);
      setData(Array.isArray(res) ? res : []);
    } catch (e: any) {
      Alert.alert(
        "Error",
        e?.response?.data?.message || e?.message || "Failed to load vouchers"
      );
    } finally {
      setLoading(false);
    }
  }, [fromDate, toDate, typeFilter]);

  const onRefresh = useCallback(async () => {
    setRefreshing(true);
    await load();
    setRefreshing(false);
  }, [load]);

  useEffect(() => {
    if (isFocused) load();
  }, [isFocused, load]);

  const onDelete = (voucher: Voucher) => {
    const ref = voucher.reference_no ?? "";
    if (ref.startsWith("BILL:") || ref.startsWith("REFUND:")) {
      Alert.alert(
        "Not allowed",
        "This voucher was auto-generated by a bill/refund flow. Delete or reverse that source entry instead."
      );
      return;
    }

    Alert.alert("Delete Voucher", `Delete ${voucher.voucher_no}?`, [
      { text: "Cancel" },
      {
        text: "Delete",
        style: "destructive",
        onPress: async () => {
          try {
            await deleteVoucher(voucher.voucher_id);
            setData((prev) => prev.filter((v) => v.voucher_id !== voucher.voucher_id));
          } catch (e: any) {
            Alert.alert(
              "Error",
              e?.response?.data?.message || e?.message || "Cannot delete"
            );
          }
        },
      },
    ]);
  };

  const renderItem = ({ item }: { item: Voucher }) => {
    const vType = item.voucher_type as VoucherType;
    const typeColor = TYPE_COLOR[vType] ?? "#6B7280";
    const isAuto =
      (item.reference_no ?? "").startsWith("BILL:") ||
      (item.reference_no ?? "").startsWith("REFUND:");
    const total = Number(item.total_dr ?? 0);

    return (
      <TouchableOpacity
        activeOpacity={0.85}
        style={[
          styles.card,
          {
            backgroundColor: colors.surface,
            borderColor: colors.border,
            borderLeftColor: typeColor,
            borderLeftWidth: 4,
          },
        ]}
        onPress={() =>
          navigation.navigate("VoucherEntry", { voucherId: item.voucher_id })
        }
        onLongPress={() => onDelete(item)}
      >
        <View style={styles.topRow}>
          <View style={{ flex: 1 }}>
            <Text style={[styles.voucherNo, { color: colors.text }]}>
              {item.voucher_no}
            </Text>
            <Text style={[styles.dateText, { color: colors.textSecondary }]}>
              {formatDateTime(item.voucher_date)}
            </Text>
          </View>

          <View style={styles.badgesRow}>
            {isAuto && (
              <View style={[styles.badge, { backgroundColor: "#D98E0418" }]}>
                <Text style={[styles.badgeText, { color: "#D98E04" }]}>Auto</Text>
              </View>
            )}
            <View style={[styles.badge, { backgroundColor: `${typeColor}18` }]}>
              <Text style={[styles.badgeText, { color: typeColor }]}>{vType}</Text>
            </View>
          </View>
        </View>

        {item.narration ? (
          <Text
            style={[styles.narration, { color: colors.textSecondary }]}
            numberOfLines={1}
          >
            {item.narration}
          </Text>
        ) : null}

        {item.reference_no ? (
          <Text style={[styles.meta, { color: colors.textSecondary }]}>
            Ref: {item.reference_no}
          </Text>
        ) : null}

        {total > 0 ? (
          <Text style={[styles.amount, { color: typeColor }]}>
            ₹ {formatNumber(total, 2)}
          </Text>
        ) : null}

        <Text style={[styles.hint, { color: colors.textSecondary }]}>
          Tap to view/edit · Long press to delete
        </Text>
      </TouchableOpacity>
    );
  };

  if (loading && !refreshing && data.length === 0) return <Loader />;

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <SectionTitle
        title="Vouchers"
        subtitle={`${data.length} voucher${data.length === 1 ? "" : "s"}`}
        rightContent={
          <AppButton
            title="+ New"
            size="small"
            onPress={() => navigation.navigate("VoucherEntry", {})}
          />
        }
      />

      <View style={styles.filterRow}>
        {TYPE_FILTERS.map((f) => (
          <Pill
            key={f}
            label={f}
            active={typeFilter === f}
            onPress={() => setTypeFilter(f)}
          />
        ))}
      </View>

      <View style={styles.dateRow}>
        <TouchableOpacity
          style={[
            styles.datePill,
            { backgroundColor: colors.surface, borderColor: colors.border },
          ]}
          onPress={() => setShowFrom(true)}
        >
          <Text style={[styles.dateLabel, { color: colors.textSecondary }]}>
            From
          </Text>
          <Text style={[styles.dateValue, { color: colors.text }]}>{fromDate}</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={[
            styles.datePill,
            { backgroundColor: colors.surface, borderColor: colors.border },
          ]}
          onPress={() => setShowTo(true)}
        >
          <Text style={[styles.dateLabel, { color: colors.textSecondary }]}>To</Text>
          <Text style={[styles.dateValue, { color: colors.text }]}>{toDate}</Text>
        </TouchableOpacity>

        <AppButton title="Go" size="small" onPress={load} style={{ alignSelf: "center" }} />
      </View>

      {showFrom && (
        <DateTimePicker
          value={new Date(fromDate)}
          mode="date"
          display={Platform.OS === "ios" ? "spinner" : "default"}
          onChange={(_, d) => {
            setShowFrom(false);
            if (d) {
              setFromDate(
                new Intl.DateTimeFormat("en-CA", {
                  timeZone: "Asia/Kolkata",
                  year: "numeric",
                  month: "2-digit",
                  day: "2-digit",
                }).format(d)
              );
            }
          }}
        />
      )}

      {showTo && (
        <DateTimePicker
          value={new Date(toDate)}
          mode="date"
          display={Platform.OS === "ios" ? "spinner" : "default"}
          onChange={(_, d) => {
            setShowTo(false);
            if (d) {
              setToDate(
                new Intl.DateTimeFormat("en-CA", {
                  timeZone: "Asia/Kolkata",
                  year: "numeric",
                  month: "2-digit",
                  day: "2-digit",
                }).format(d)
              );
            }
          }}
        />
      )}

      <FlatList
        data={data}
        keyExtractor={(item) => String(item.voucher_id)}
        renderItem={renderItem}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}
        ListEmptyComponent={
          !loading ? (
            <View
              style={[
                styles.emptyCard,
                { backgroundColor: colors.surface, borderColor: colors.border },
              ]}
            >
              <Text style={[styles.emptyTitle, { color: colors.text }]}>
                No vouchers found
              </Text>
              <Text style={[styles.emptySubtitle, { color: colors.textSecondary }]}>
                Tap "+ New" to create a manual voucher
              </Text>
            </View>
          ) : null
        }
        contentContainerStyle={{
          paddingBottom: 24,
          flexGrow: data.length === 0 ? 1 : undefined,
        }}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  filterRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 10 },
  dateRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
    alignItems: "center",
  },
  datePill: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dateLabel: { fontSize: 11, marginBottom: 2 },
  dateValue: { fontSize: 13, fontWeight: "600" },
  card: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
  },
  topRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 6,
  },
  voucherNo: { fontSize: 15, fontWeight: "700" },
  dateText: { fontSize: 12, marginTop: 2 },
  badgesRow: { flexDirection: "row", gap: 6 },
  badge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeText: { fontSize: 11, fontWeight: "700" },
  narration: { fontSize: 13, marginBottom: 4 },
  meta: { fontSize: 12, marginBottom: 4 },
  amount: { fontSize: 16, fontWeight: "700", marginTop: 6 },
  hint: { fontSize: 11, marginTop: 6 },
  emptyCard: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  emptyTitle: { fontSize: 16, fontWeight: "700", marginBottom: 6 },
  emptySubtitle: { fontSize: 13, textAlign: "center" },
});

export default VoucherListScreen;